name: NodeJS with Webpack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          echo "export const lastCommitHash: string | undefined = \"$(git rev-parse --short HEAD)\";" > src/_git_commit.ts
          npx webpack
          git checkout src/_git_commit.ts
      - run: |
          git config user.name "Build Script"
          git config user.email "<>"
          git fetch --all
          cp data built/data -r
          git switch release
          rm -r scripts/
          rm -r data/
          rm -r relay/
          mv built/scripts scripts
          mv built/data data
          mv built/relay relay
          git add scripts/
          git add data/
          git add relay/
          git commit -m "Build Mafia files for commit $GITHUB_SHA"
          git push origin release
